// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Delivery struct {
	OrderUid string
	Name     string
	Phone    string
	Zip      string
	City     string
	Address  string
	Region   string
	Email    string
}

type Item struct {
	ItemID      int32
	OrderUid    string
	ChrtID      int32
	TrackNumber string
	Price       int32
	Rid         string
	Name        string
	Sale        int32
	Size        string
	TotalPrice  int32
	NmID        int32
	Brand       string
	Status      int32
}

type Order struct {
	OrderUid          string
	TrackNumber       string
	Entry             string
	Locale            string
	InternalSignature sql.NullString
	CustomerID        string
	DeliveryService   string
	Shardkey          string
	SmID              int32
	DateCreated       time.Time
	OofShard          string
}

type Payment struct {
	OrderUid     string
	Transaction  string
	RequestID    sql.NullString
	Currency     string
	Provider     string
	Amount       int32
	PaymentDt    int64
	Bank         string
	DeliveryCost int32
	GoodsTotal   int32
	CustomFee    int32
}
